### Insert a company
POST https://localhost:7208/api/companies
Content-Type: application/json

{
  "Name": "Company Name",
  "Address": "Company Address",
  "UserId": "1"
}

### Get a company
GET https://localhost:7208/api/companies/{id}

### Get all companies
GET https://isia2j0uf8.execute-api.us-east-1.amazonaws.com/production/api/companies
Content-Type: application/json

### Update Company
PUT https://localhost:7208/api/companies/{id}
Content-Type: application/json

{
    "name": "New Company Name",
    "address": "New Company Address"
}

### Delete Company
DELETE https://localhost:7208/api/companies/{id}

### Get Companies by User ID
GET https://localhost:7208/api/companies/user/{userId}