### Register a new user
POST https://isia2j0uf8.execute-api.us-east-1.amazonaws.com/production/api/users/register
Content-Type: application/json

{
    "username": "newuser",
    "password": "password"
}

### Login a user
POST https://isia2j0uf8.execute-api.us-east-1.amazonaws.com/production/api/users/login
Content-Type: application/json

{
    "username": "mudassarm30",
    "password": "business"
}

### Get a company
GET https://isia2j0uf8.execute-api.us-east-1.amazonaws.com/production/api/companies/{id}

### Get all companies
GET https://isia2j0uf8.execute-api.us-east-1.amazonaws.com/production/api/companies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXVkYXNzYXJtMzAiLCJuYmYiOjE3MDEyMTcxODksImV4cCI6MTcwMTgyMTk4OSwiaWF0IjoxNzAxMjE3MTg5LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.8ZYTXrB167zVsbRmFztYvOU25X12lBntX0HrXOpzN48

### Update Company
PUT https://isia2j0uf8.execute-api.us-east-1.amazonaws.com/production/api/companies/{id}
Content-Type: application/json

{
    "name": "New Company Name",
    "address": "New Company Address"
}

### Delete Company
DELETE https://isia2j0uf8.execute-api.us-east-1.amazonaws.com/production/api/companies/{id}

### Get Companies by User ID
GET https://isia2j0uf8.execute-api.us-east-1.amazonaws.com/production/api/companies/user/{userId}

### Login a user
POST https://localhost:7208/api/users/login
Content-Type: application/json

{
    "username": "mudassarm30",
    "password": "business"
}


### Get companies list
GET https://localhost:7208/api/companies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXVkYXNzYXJtMzAiLCJuYmYiOjE3MDEyMTY5MjIsImV4cCI6MTcwMTgyMTcyMiwiaWF0IjoxNzAxMjE2OTIyLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.x6a920nP65Il-WWP2T-VaNYcCf-vQIzy1xw_k1DJhGo