name: Centralized Deploy

on:
  push:
    branches:
      - csharp
      - java
      - python
      - php

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Trigger Deployment Workflow
      run: |
        if [ "${{ github.ref }}" == "refs/heads/csharp" ]; then
          echo "Triggering C# Deployment"
          cat csharp/deploy.yml >> .github/workflows/deploy.yml
        elif [ "${{ github.ref }}" == "refs/heads/java" ]; then
          echo "Triggering Java Deployment"
          cat java/deploy.yml >> .github/workflows/deploy.yml
        elif [ "${{ github.ref }}" == "refs/heads/python" ]; then
          echo "Triggering Python Deployment"
          cat python/deploy.yml >> .github/workflows/deploy.yml
        elif [ "${{ github.ref }}" == "refs/heads/php" ]; then
          echo "Triggering PHP Deployment"
          cat php/deploy.yml >> .github/workflows/deploy.yml
        else
          echo "No changes in supported branches. Skipping deployment."
        fi

    - name: Execute Deploy
      run: |
        source .github/workflows/deploy.yml
